reopen-branch

diff --git a/.github/workflows/envoy-release.yml b/.github/workflows/envoy-release.yml
--- a/.github/workflows/envoy-release.yml
+++ b/.github/workflows/envoy-release.yml
@@ -19,6 +19,7 @@ on:
         type: choice
         options:
         - create-release
+        - reopen-branch
         - sync-version-histories
         - deprecate-guards
       dry-run:
@@ -56,6 +57,87 @@ jobs:
     runs-on: ubuntu-22.04
     if: github.event_name == 'workflow_dispatch' && inputs.task == 'create-release'
     name: Create release
+    steps:
+    - id: appauth
+      name: App auth
+      uses: envoyproxy/toolshed/gh-actions/appauth@actions-v0.3.13
+      with:
+        app_id: ${{ secrets.ENVOY_CI_PUBLISH_APP_ID }}
+        key: ${{ secrets.ENVOY_CI_PUBLISH_APP_KEY }}
+
+    - id: checkout
+      name: Checkout Envoy repository
+      uses: envoyproxy/toolshed/gh-actions/github/checkout@actions-v0.3.13
+      with:
+        committer-name: ${{ env.COMMITTER_NAME }}
+        committer-email: ${{ env.COMMITTER_EMAIL }}
+        strip-prefix: release/
+        token: ${{ steps.appauth.outputs.token }}
+    - run: |
+        if [[ ! -s "changelogs/summary.md" ]]; then
+            if [[ "${{ inputs.summary }}" == "false" ]]; then
+                echo "::warning::Changelog summary (changelogs/summary.md) is empty!"
+                exit 0
+            fi
+            echo "::error::Changelog summary (changelogs/summary.md) is empty!"
+            exit 1
+        fi
+        COMMITTER=$(git log -n 1 --format='%an <%ae>' -- changelogs/summary.md)
+        echo "committer=${COMMITTER}" >> $GITHUB_OUTPUT
+      id: changelog
+      name: Check changelog summary
+    - if: ${{ inputs.author }}
+      name: Validate signoff email
+      uses: envoyproxy/toolshed/gh-actions/email/validate@actions-v0.3.13
+      with:
+        email: ${{ inputs.author }}
+    - uses: envoyproxy/toolshed/gh-actions/github/run@actions-v0.3.13
+      name: Create release
+      with:
+        source: |
+          BAZEL_ARGS=(--)
+          BAZEL_RUN_ARGS=(--config=ci)
+          if [[ -n "${{ inputs.author }}" ]]; then
+              BAZEL_ARGS+=(
+                  "--release-author=${{ inputs.author }}"
+                  "--signoff=${{ steps.changelog.outputs.committer }}")
+          else
+              BAZEL_ARGS+=("--release-author=${{ steps.changelog.outputs.committer }}")
+          fi
+        command: >-
+          bazel
+          run
+          "${BAZEL_RUN_ARGS[@]}"
+          @envoy_repo//:release
+          "${BAZEL_ARGS[@]}"
+    - run: |
+        VERSION=$(cat VERSION.txt)
+        echo "version=v${VERSION}" >> $GITHUB_OUTPUT
+      name: Release version
+      id: release
+    - name: Create a PR
+      uses: envoyproxy/toolshed/gh-actions/github/pr@actions-v0.3.13
+      with:
+        base: ${{ github.ref_name }}
+        commit: false
+        append-commit-message: true
+        body: |
+          Created by Envoy publish bot for @${{ github.actor }}
+          ${{ ! inputs.summary && ':warning: Created without changelog summary, this will need to be updated before publishing' || '' }}
+        branch: release/create/${{ steps.checkout.outputs.branch-name }}
+        diff-upload: release-${{ steps.checkout.outputs.branch-name }}
+        diff-show: true
+        dry-run: ${{ ! inputs.pr }}
+        wip: ${{ ! inputs.summary || inputs.wip }}
+        title: >-
+          [${{ (! inputs.summary || inputs.wip) && 'WIP/' || '' }}release/${{ steps.checkout.outputs.branch-name }}]
+          repo: Release ${{ steps.release.outputs.version }}
+        GITHUB_TOKEN: ${{ steps.appauth.outputs.token }}
+
+  reopen_branch:
+    runs-on: ubuntu-22.04
+    if: github.event_name == 'workflow_dispatch' && inputs.task == 'reopen-branch'
+    name: Reopen branch
     steps:
     - id: appauth
       name: App auth
